name: machine-learning-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.21.0
  - pandas=1.3.0
  - matplotlib=3.4.0
  - seaborn=0.11.0
  - scikit-learn=0.24.0
  - xgboost=1.5.0
  - tensorflow=2.8.0
  - scipy=1.7.0
  - joblib=1.0.1
  - pip:
    - keras==2.8.0  # For compatibility with tensorflow